plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

# ================ LAYOUT ==============
Layout/LineLength:
  Max: 150

# ================ LINT ================
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Lint/EmptyClass:
  Exclude:
    - spec/**/*_spec.rb

# ================ Metics ================
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snfoil-policy.gemspec

# ================ RSPEC ================
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# ================ STYLE ================
Style/OpenStructUse:
  Exclude:
    - spec/**/*.rb