services:
  workspace:
    build:
      context: .
      target: base
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    env_file:
      - path: .env
        required: false